// <auto-generated />
using System;
using Genealogy.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Genealogy.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Genealogy.Api.Models.Marriage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DivorceDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("MarriageDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarriagePlace")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpouseAId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpouseBId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpouseBId");

                    b.HasIndex("SpouseAId", "SpouseBId")
                        .IsUnique();

                    b.ToTable("Marriages", t =>
                        {
                            t.HasCheckConstraint("CK_Marriage_DistinctSpouses", "SpouseAId <> SpouseBId");
                        });
                });

            modelBuilder.Entity("Genealogy.Api.Models.ParentChild", b =>
                {
                    b.Property<Guid>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("TEXT");

                    b.HasKey("ParentId", "ChildId");

                    b.HasIndex("ChildId");

                    b.ToTable("ParentChildren");
                });

            modelBuilder.Entity("Genealogy.Api.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeathPlace")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Surname", "GivenName");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Genealogy.Api.Models.Marriage", b =>
                {
                    b.HasOne("Genealogy.Api.Models.Person", "SpouseA")
                        .WithMany("MarriagesA")
                        .HasForeignKey("SpouseAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Genealogy.Api.Models.Person", "SpouseB")
                        .WithMany("MarriagesB")
                        .HasForeignKey("SpouseBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SpouseA");

                    b.Navigation("SpouseB");
                });

            modelBuilder.Entity("Genealogy.Api.Models.ParentChild", b =>
                {
                    b.HasOne("Genealogy.Api.Models.Person", "Child")
                        .WithMany("Parents")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Genealogy.Api.Models.Person", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Genealogy.Api.Models.Person", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MarriagesA");

                    b.Navigation("MarriagesB");

                    b.Navigation("Parents");
                });
#pragma warning restore 612, 618
        }
    }
}
